### ISSUE TITLE
elaravel.sql doesnt exit

### ISSUE THREAD

**Issue by MostefaBoudjema** [HiImPhong/E-commerce-Furniture-With-PHP-Laravel-BaseProject2#1]
some of the tables are missing in the migration folder

**Comment by FOG-ntp** [comment]
i just uploaded the elaravel.sql file, thank you for your interest😊👌

**Comment by FOG-ntp** [comment]
> some of the tables are missing in the migration folder



> some of the tables are missing in the migration folder



> some of the tables are missing in the migration folder

i just uploaded the elaravel.sql file, thank you for your interest😊👌

**Comment by FOG-ntp** [comment]
You can create an issue for that in my project, we can talk more easily!

Vào Th 2, 29 thg 8, 2022 vào lúc 16:24 Mostfa ***@***.***>
đã viết:
