### ISSUE TITLE
Website is not launching after following the steps provided

### ISSUE THREAD

**Issue by MakabiDev** [HiImPhong/E-commerce-Furniture-With-PHP-Laravel-BaseProject2#2]
This is regarding your ecomerce project,  what the version of PHP used ?
I tried building on php7.4 and getting error:

Warning: require_once(C:\Personnel\Ecommerce-website-in-Laravel-main/public/index.php): Failed to open stream: No such file or directory in C:\Personnel\Ecommerce-website-in-Laravel-main\server.php on line 21

Fatal error: Uncaught Error: Failed opening required 'C:\Personnel\Ecommerce-website-in-Laravel-main/public/index.php' (include_path='.;c:\php\includes') in C:\Personnel\Ecommerce-website-in-Laravel-main\server.php:21 Stack trace: #0 {main} thrown in C:\Personnel\Ecommerce-website-in-Laravel-main\server.php on line 21

Can you please support here

**Comment by FOG-ntp** [comment]
> ```
>  This is regarding your ecomerce project,  what the version of PHP used ?
> ```
> 
> I tried building on php7.4 and getting error:
> 
> Warning: require_once(C:\Personnel\Ecommerce-website-in-Laravel-main/public/index.php): Failed to open stream: No such file or directory in C:\Personnel\Ecommerce-website-in-Laravel-main\server.php on line 21
> 
> Fatal error: Uncaught Error: Failed opening required 'C:\Personnel\Ecommerce-website-in-Laravel-main/public/index.php' (include_path='.;c:\php\includes') in C:\Personnel\Ecommerce-website-in-Laravel-main\server.php:21 Stack trace: #0 {main} thrown in C:\Personnel\Ecommerce-website-in-Laravel-main\server.php on line 21
> 
> Can you please support here

The version of PHP used is 5.8, for your problem i think you can copy index.php from a fresh installation of the version that you have

**Comment by MakabiDev** [comment]
is there a php 5.8 version available ?  5.6 and then 7.0 i guess there is no 5.8 version.
Can you reverify and confirm if possible can you attach the php verison.
Also the composer.json has the below:
 "require": {
        "php": "^7.3|^8.0",
        "laravel/framework": "^8.54",
    },
